### ISSUE TITLE
0 fusion cards found

### ISSUE THREAD

**Issue by simonrule** [ignaciora/yugioh-fusion-helper#1]
could you please update your script

**Comment by derpierre65** [comment]
@simonrule
i created a new one as web version, so no download is required, if someone is interested: https://yugioh-fusion-helper.pages.dev/

**Comment by ignaciora** [comment]
> @simonrule i created a new one as web version, so no download is required, if someone is interested: https://yugioh-fusion-helper.pages.dev/

Nice project!! Thanks @derpierre65 ! :)

**Comment by ignaciora** [comment]
> could you please update your script

Sorry but i guess it will be better to use @derpierre65 website now ( [ https://yugioh-fusion-helper.pages.dev/](url) ). Anyway I'm closing this issue due to a lack of info to reproduce the error.
